version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: stocklee-postgres
    environment:
      POSTGRES_DB: stocklee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  stocklee-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stocklee-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stocklee
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres