spring:
  application:
    name: stocklee

  datasource:
    url: jdbc:h2:mem:devdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: true

  flyway:
    enabled: false

  thymeleaf:
    cache: false
    check-template-location: false

server:
  port: 8080

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.springframework: INFO
    com.tinusj.stocklee: INFO
    org.hibernate.SQL: INFO

stocklee:
  scheduler:
    market-data-fetch-cron: "0 */30 * * * *"  # Every 30 minutes

# External APIs Configuration
alphavantage:
  api:
    key: demo  # Replace with actual AlphaVantage API key for production

nasdaq:
  api:
    key: demo  # Replace with actual Nasdaq API key for production
    base-url: https://api.nasdaq.com