spring:
  application:
    name: stocklee

  datasource:
    url: jdbc:postgresql://localhost:5432/stocklee
    username: postgres
    password: "@Tinus"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  thymeleaf:
    cache: false
    check-template-location: false

server:
  port: 8080

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.springframework: INFO
    com.tinusj.stocklee: DEBUG
    org.hibernate.SQL: DEBUG

stocklee:
  scheduler:
    market-data-fetch-cron: "0 */30 * * * *"  # Every 30 minutes

# External APIs Configuration
alphavantage:
  api:
    key: demo  # Replace with actual AlphaVantage API key for production