name: Build, Test, and Validate (PRs to Main)

on:
  pull_request:
    branches:
      - main

jobs:
  build-test-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    - name: Build and test
      run: mvn clean verify

    - name: Start application
      run: |
        nohup mvn spring-boot:run &
        sleep 30

    - name: Validate application health
      run: curl --fail http://localhost:8080/actuator/health

    - name: Stop application
      run: pkill -f 'mvn spring-boot:run' || true